#
# Use with docker-compose.yml to change the discovery backed to consul
#

version: "2"

services:

    discovery:
        image: gliderlabs/consul-server:0.5
        command: ["-bootstrap"]

    swarm.master:
        environment:
            SWARM_DISCOVERY: "consul://discovery:8500/"

    swarm.slave:
        environment:
            SWARM_DISCOVERY: "consul://discovery:8500/"
